[[constraint]]
  name = "cloud.google.com/go"
  version = "0.28.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.46"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[prune]
  go-tests = true
  unused-packages = true
