apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-billing-exporter.fullname" . }}
  labels:
    {{- include "cloud-billing-exporter.labels" . | nindent 4 }}
type: Opague
data:
{{- range $key, $value := .Values.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- if .Values.googleServiceAccount }}
  google-service-account: {{ .Values.googleServiceAccount | b64enc | quote }}
{{- end }}
