apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-billing-exporter.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
  labels:
    {{- include "cloud-billing-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloud-billing-exporter.selectorLabels" . | nindent 4 }}
