on: [push, pull_request]
name: Lint & Build & Test
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.4
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Lint
      run: make lint

  test:
    strategy:
      matrix:
        go-version: [1.13.4]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build
      run: make build
    - name: Test
      run: make test
